version: '3.7'

volumes:
  postgres: {}

services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    stop_signal: SIGINT
    environment:
      LC_ALL: 'C.UTF-8'
      POSTGRES_DB: 'demo-up-cliplister-db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '${PG_PASSWD:-postgres}'
    ports:
      - '${PG_PORT:-5432}:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
